### PR TITLE
Clean up and package for https://pypi.org/project/suql/

### PR DESCRIPTION
**Pull request by george1459**
Main changes:
- Deleted all unnecessary restaurants-related code. Remaining restaurants code provided as reference for building agents are explicitly labelled with comprehensive doc-strings
- Modified username/pswd so that only the entry point arguments need to be changed
- All servers are packaged for easy set-up and import
- README changes to two options: (1) install from source; (2) install from `pip`

### CODE REVIEW

**Comment by duskybomb** [comment]
I cannot find conv_agent.md file (https://github.com/stanford-oval/suql/blob/wip/cleanup-package/docs/conv_agent.md). It shows 404

**Comment by george1459** [comment]
Just added - thanks

**Comment by george1459** [comment]
@duskybomb What is the format checker called again?

**Comment by duskybomb** [comment]
Its `black` formatter and using `isort` as well.

**Pull request merged**
